<a href="https://colab.research.google.com/github/liangchow/zindi-amazon-secret-runway/blob/explore-sentinel1-data/Data_Visualization/explore_sentinel1_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Working with github: [A guide from Google](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)

### Imports and Setup.

In [1]:
%%capture
!pip -q install geojson
!pip -q install rasterio
!pip -q install eeconvert
!pip -q install geemap==0.17.3

In [2]:
# Standard imports
import os
import json

# Geospatial processing packages
import geopandas as gpd
import geojson
import shapely
import calendar
from shapely.geometry import box
from shapely.geometry import Polygon, Point
from pyproj import Transformer

# Mapping and plotting libraries
import ee
import eeconvert as eec
import geemap
import geemap.eefolium as emap
import folium

### Authenticate Google Earth Engine
Make sure you have signed up for access to Google Earth Engine. You will need to edit the following code cell to use your own account. All the Sentinel data will be downloaded through the Google Earth Engine.

In [3]:
# Load the service account key
service_account = 'earth-engine-sa@ee-runway-detection.iam.gserviceaccount.com'
credentials = ee.ServiceAccountCredentials(service_account, '/content/ee-runway-detection-ce5179ca616c.json')

# Authenticate with Earth Engine using the service account
ee.Initialize(credentials)

### Mount your Google Drive and install project files

First, we'll mount your Google Drive. Then we'll clone the main branch from the GitHub repo so we have access to all of the files from there.

In [4]:
# mount your drive in case you have any new data uploaded there you want to use
from google.colab import drive
drive.mount('/content/drive')

# clone the main branch from GitHub to get all the data and files from there onto the current runtime session
!apt-get install git
!git clone https://github.com/liangchow/zindi-amazon-secret-runway.git
!git pull # pulls the latest changes from repo

Mounted at /content/drive
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.11).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.
Cloning into 'zindi-amazon-secret-runway'...
remote: Enumerating objects: 138, done.
remote: Counting objects: 100% (138/138), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 138 (delta 38), reused 8 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (138/138), 758.05 KiB | 3.72 MiB/s, done.
Resolving deltas: 100% (38/38), done.
fatal: not a git repository (or any of the parent directories): .git

### Setup paths to the project files

In [5]:
airstrip_training_path = '/content/zindi-amazon-secret-runway/Data_Visualization/data/pac_2024_training/pac_2024_training.shp'
base_aoi_path = '/content/zindi-amazon-secret-runway/Data_Visualization//data/shp_test_AOIs'

# Select export folder on Google Drive
export_folder = 'Colab Notebooks'

In [6]:
# Read the shapefile for the training dataset
airstrip_training_gdf = gpd.read_file(airstrip_training_path)
airstrip_training_gdf.head(1)

,id,yr,largo,Activo,geometry
0,1,2023,968.918,0,"LINESTRING (-70.08929 -13.12984, -70.08053 -13..."

In [7]:
# Reproject the data to World Mercator projection
projected_airstrip_training_gdf = airstrip_training_gdf.to_crs(epsg=3395)
projected_airstrip_training_gdf.head(1)

,id,yr,largo,Activo,geometry
0,1,2023,968.918,0,"LINESTRING (-7802303.691 -1464870.283, -780132..."

### Download Sentinel1 Image Collection

Sentinel-1 collects C-band synthetic aperture radar (SAR) imagery at a variety of polarizations and resolutions. [Read more](https://developers.google.com/earth-engine/guides/sentinel1) about filtering the data to a homogenous susbet.



- Different polarization combinations are more and less sensitive to different kinds landcover features and phenomena. For example VV modes tend to pick up height/vertical features where VH modes tend to be more sensitive to surface textures. (Source)[https://support.capellaspace.com/hc/en-us/articles/360044738831-Sentinel-1-Polarization]

- For this application the most suitable product is the Interferometric Wide with dual polarisation. In fact, the cross-polarisation VH is more sensitive to change in vegetation density and structure while the polarisation ratio VH/VV is an important index for vegetation phenology or water content (European Wide Forest Classification Based on Sentinel-1 Data). (Source)[https://sentiwiki.copernicus.eu/web/s1-applications#S1Applications-ForestryS1-Applications-Forestry]

- Different polarization combinations provide different and complementary information about the surface features. For example, linearly oriented structures such as buildings or ripples in the sand tend to reflect and preserve the coherence (same linear direction) of the polarimetric signal. Randomly oriented structures such as tree leaves scatter and depolarize the signal as it bounces multiple times. (Source)[https://medium.com/@pulakeshpradhan/sentinel-1-sar-data-processing-2dd9b2751d95]

In [8]:
# Function to calculate VV/VH ratio and add it as a new band
def add_vv_vh_ratio(image):
    ratio_band = image.select('VV').divide(image.select('VH')).rename('VV_VH_Ratio')
    return image.addBands(ratio_band)

In [9]:
# Function to rename band
def rename_bands(image, suffix):
    # Get the original band names
    original_band_names = image.bandNames()

    # Create new band names using server-side expression
    new_band_names = original_band_names.map(lambda band: ee.String(band).cat('_').cat(suffix))

    # Rename all bands
    renamed_image_all = image.rename(new_band_names)

    return image.rename(new_band_names)

In [10]:
# Function to convert bands to Float32 to reduce file size
def to_float(image):
    return image.toFloat()

In [22]:
def download_sentinel1_data(aoi, id, year=2023):

  # Load Sentinel-1 data for ascending and descending orbits
  sentinel1 = ee.ImageCollection('COPERNICUS/S1_GRD') \
    .filterBounds(aoi) \
    .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV')) \
    .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VH')) \
    .filter(ee.Filter.eq('instrumentMode', 'IW'))

  count = sentinel1.size()
  print(f'Number of images in the collection: {count.getInfo()}')

  #combined_composite = []
  info = []

  # Process and export monthly composites
  for month in range(1, 13):
      # Define start and end dates for the month
      start_date = ee.Date.fromYMD(year, month, 1)
      end_date = ee.Date.fromYMD(year, month, calendar.monthrange(year, month)[1])

      # Filter Sentinel-1 data for the current month
      monthly_data_ascending = sentinel1.filterDate(start_date, end_date) \
                                        .filter(ee.Filter.eq('orbitProperties_pass', 'ASCENDING')) \
                                        .map(lambda img: add_vv_vh_ratio(img)) \
                                        .map(lambda img: rename_bands(img, 'Asc')) \
                                        .map(lambda img: to_float(img))
      #print(f'Number of images in the monthly_data_ascending: {monthly_data_ascending.size().getInfo()}')

      monthly_data_descending = sentinel1.filterDate(start_date, end_date) \
                                        .filter(ee.Filter.eq('orbitProperties_pass', 'DESCENDING')) \
                                        .map(lambda img: add_vv_vh_ratio(img)) \
                                        .map(lambda img: rename_bands(img, 'Desc')) \
                                        .map(lambda img: to_float(img))
      #print(f'Number of images in the monthly_data_descending: {monthly_data_descending.size().getInfo()}')

      info.append({
          'id': id,
          'month': calendar.month_name[month],
          'month_asc': monthly_data_ascending.size().getInfo(),
          'month_desc': monthly_data_descending.size().getInfo()
      })

  return info
      # Calculate median composite for the current month
      # composite_ascending = monthly_data_ascending.median().clip(aoi)
      # composite_descending = monthly_data_descending.median().clip(aoi)

      # # Combine ascending and descending composites into a single multi-band image
      # # combined_composite.append(composite_ascending.addBands(composite_descending))
      # combined_composite = composite_ascending.addBands(composite_descending)

      # # Define the export description and file name prefix
      # export_description = f'Sentinel1_Combined_Composite_{id}_{year}_{month:02d}'
      # file_name_prefix = f'Sentinel1_Composite_{id}_{year}_{month:02d}'

      # # # Export the combined composite to Google Drive
      # task = ee.batch.Export.image.toDrive(
      #     image=combined_composite,
      #     description=export_description,
      #     folder='GEE_Exports',
      #     fileNamePrefix=file_name_prefix,
      #     scale=10,
      #     region=aoi,
      #     maxPixels=1e13,
      #     fileFormat='GeoTIFF'
      # )

      # # Start the export task
      # task.start()

      # print(f'Export task for {calendar.month_name[month]} started. Check your Google Drive for the exported image.')

### Loop over all runways

In [12]:
# Helper function to convert geopandas feature geometry to Earth Engine geometry for plotting
def gpd_geometry_to_ee_geometry(gpd_geometry, target_crs='EPSG:3395'):
  # Convert the reprojected GeoPandas geometry to GeoJSON-like format
  geojson_geometry = gpd_geometry.__geo_interface__

  # Define the CRS
  crs = ee.Projection(target_crs)

  # Convert the GeoJSON geometry to Earth Engine geometry
  ee_geometry = ee.Geometry(geojson_geometry, proj=crs)

  return ee_geometry

In [26]:
def get_imagelist_by_airstrip(airstrip_gpd):
  # Get information from the airstrip
  year = int(airstrip_gpd.yr)
  id = airstrip_gpd.id
  airstrip_gpd_geometry = airstrip_gpd.geometry

  # Create a square buffer at a distance of 5 km around centroid of airstrip
  buffer_gpd = Point(airstrip_gpd_geometry.centroid).buffer(1000, cap_style=3)

  # Convert GeoPandas geometry to Earth Engine features
  airstrip_ee = gpd_geometry_to_ee_geometry(airstrip_gpd_geometry)
  buffer_ee = gpd_geometry_to_ee_geometry(buffer_gpd)

  # Download monthly composites
  # GEE expects the aoi to be in geogprahic coordinates to filter the image collection
  # img = download_sentinel1_data(buffer_ee, id)
  image_list = download_sentinel1_data(buffer_ee, id)
  return image_list

In [28]:
# Iterate through each feature using .iterrows()
data = []
for index, row in projected_airstrip_training_gdf.iterrows():
  #year = int(row.yr)
  #id = row.id
  image_list = get_imagelist_by_airstrip(row)
  #image_list = {'id': id, 'year': year }
  data.append(image_list)

data

Number of images in the collection: 432
Number of images in the collection: 509
Number of images in the collection: 493
Number of images in the collection: 493
Number of images in the collection: 493
Number of images in the collection: 493
Number of images in the collection: 430
Number of images in the collection: 430
Number of images in the collection: 662
Number of images in the collection: 587
Number of images in the collection: 610
Number of images in the collection: 419
Number of images in the collection: 419
Number of images in the collection: 419
Number of images in the collection: 419
Number of images in the collection: 418
Number of images in the collection: 565
Number of images in the collection: 419
Number of images in the collection: 419
Number of images in the collection: 418
Number of images in the collection: 645
Number of images in the collection: 586
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 585
Number of images in the collection: 376
Number of images in the collection: 398
Number of images in the collection: 398
Number of images in the collection: 398
Number of images in the collection: 453
Number of images in the collection: 397
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 573
Number of images in the collection: 573
Number of images in the collection: 573
Number of images in the collection: 573
Number of images in the collection: 574
Number of images in the collection: 576
Number of images in the collection: 576
Number of images in the collection: 547
Number of images in the collection: 500
Number of images in the collection: 500
Number of images in the collection: 500
Number of images in the collection: 500
Number of images in the collection: 345
Number of images in the collection: 399
Number of images in the collection: 525
Number of images in the collection: 408
Number of images in the collection: 398
Number of images in the collection: 524
Number of images in the collection: 523
Number of images in the collection: 397
Number of images in the collection: 398
Number of images in the collection: 397
Number of images in the collection: 397
Number of images in the collection: 397
Number of images in the collection: 397
Number of images in the collection: 396
Number of images in the collection: 396
Number of images in the collection: 398
Number of images in the collection: 396
Number of images in the collection: 398
Number of images in the collection: 398
Number of images in the collection: 473
Number of images in the collection: 398
Number of images in the collection: 472
Number of images in the collection: 398
Number of images in the collection: 398
Number of images in the collection: 397
Number of images in the collection: 474
Number of images in the collection: 397
Number of images in the collection: 397
Number of images in the collection: 397
Number of images in the collection: 397
Number of images in the collection: 397
Number of images in the collection: 395
Number of images in the collection: 395
Number of images in the collection: 397
Number of images in the collection: 397
Number of images in the collection: 397
Number of images in the collection: 406
Number of images in the collection: 397
Number of images in the collection: 397
Number of images in the collection: 376
Number of images in the collection: 598
Number of images in the collection: 598
Number of images in the collection: 587
Number of images in the collection: 398
Number of images in the collection: 398
Number of images in the collection: 358
Number of images in the collection: 430
Number of images in the collection: 800
Number of images in the collection: 419
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 397
Number of images in the collection: 475
Number of images in the collection: 634
Number of images in the collection: 391
Number of images in the collection: 507
Number of images in the collection: 496
Number of images in the collection: 382
Number of images in the collection: 831
Number of images in the collection: 383
Number of images in the collection: 383
Number of images in the collection: 383
Number of images in the collection: 596
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 417
Number of images in the collection: 573
Number of images in the collection: 397
Number of images in the collection: 397
Number of images in the collection: 398
Number of images in the collection: 526
Number of images in the collection: 521
Number of images in the collection: 356
Number of images in the collection: 345
Number of images in the collection: 532
Number of images in the collection: 521
Number of images in the collection: 502
Number of images in the collection: 500
Number of images in the collection: 397
Number of images in the collection: 398
Number of images in the collection: 398
Number of images in the collection: 407
Number of images in the collection: 397
Number of images in the collection: 473
Number of images in the collection: 473
Number of images in the collection: 397
Number of images in the collection: 398
Number of images in the collection: 601
Number of images in the collection: 417
Number of images in the collection: 418
Number of images in the collection: 502
Number of images in the collection: 559
Number of images in the collection: 396
Number of images in the collection: 430

[[{'id': 1, 'month': 'January', 'month_asc': 3, 'month_desc': 2},
  {'id': 1, 'month': 'February', 'month_asc': 2, 'month_desc': 2},
  {'id': 1, 'month': 'March', 'month_asc': 3, 'month_desc': 3},
  {'id': 1, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 1, 'month': 'May', 'month_asc': 3, 'month_desc': 2},
  {'id': 1, 'month': 'June', 'month_asc': 1, 'month_desc': 3},
  {'id': 1, 'month': 'July', 'month_asc': 2, 'month_desc': 2},
  {'id': 1, 'month': 'August', 'month_asc': 3, 'month_desc': 3},
  {'id': 1, 'month': 'September', 'month_asc': 2, 'month_desc': 2},
  {'id': 1, 'month': 'October', 'month_asc': 2, 'month_desc': 3},
  {'id': 1, 'month': 'November', 'month_asc': 2, 'month_desc': 2},
  {'id': 1, 'month': 'December', 'month_asc': 3, 'month_desc': 3}],
 [{'id': 2, 'month': 'January', 'month_asc': 0, 'month_desc': 2},
  {'id': 2, 'month': 'February', 'month_asc': 0, 'month_desc': 2},
  {'id': 2, 'month': 'March', 'month_asc': 0, 'month_desc': 3},
  {'id': 2, 'month': 'April', 'month_asc': 0, 'month_desc': 2},
  {'id': 2, 'month': 'May', 'month_asc': 0, 'month_desc': 2},
  {'id': 2, 'month': 'June', 'month_asc': 0, 'month_desc': 3},
  {'id': 2, 'month': 'July', 'month_asc': 0, 'month_desc': 2},
  {'id': 2, 'month': 'August', 'month_asc': 0, 'month_desc': 3},
  {'id': 2, 'month': 'September', 'month_asc': 0, 'month_desc': 2},
  {'id': 2, 'month': 'October', 'month_asc': 0, 'month_desc': 3},
  {'id': 2, 'month': 'November', 'month_asc': 0, 'month_desc': 2},
  {'id': 2, 'month': 'December', 'month_asc': 0, 'month_desc': 3}],
 [{'id': 3, 'month': 'January', 'month_asc': 0, 'month_desc': 2},
  {'id': 3, 'month': 'February', 'month_asc': 0, 'month_desc': 2},
  {'id': 3, 'month': 'March', 'month_asc': 0, 'month_desc': 3},
  {'id': 3, 'month': 'April', 'month_asc': 0, 'month_desc': 2},
  {'id': 3, 'month': 'May', 'month_asc': 0, 'month_desc': 2},
  {'id': 3, 'month': 'June', 'month_asc': 0, 'month_desc': 3},
  {'id': 3, 'month': 'July', 'month_asc': 0, 'month_desc': 2},
  {'id': 3, 'month': 'August', 'month_asc': 0, 'month_desc': 3},
  {'id': 3, 'month': 'September', 'month_asc': 0, 'month_desc': 2},
  {'id': 3, 'month': 'October', 'month_asc': 0, 'month_desc': 3},
  {'id': 3, 'month': 'November', 'month_asc': 0, 'month_desc': 2},
  {'id': 3, 'month': 'December', 'month_asc': 0, 'month_desc': 3}],
 [{'id': 4, 'month': 'January', 'month_asc': 0, 'month_desc': 2},
  {'id': 4, 'month': 'February', 'month_asc': 0, 'month_desc': 2},
  {'id': 4, 'month': 'March', 'month_asc': 0, 'month_desc': 3},
  {'id': 4, 'month': 'April', 'month_asc': 0, 'month_desc': 2},
  {'id': 4, 'month': 'May', 'month_asc': 0, 'month_desc': 2},
  {'id': 4, 'month': 'June', 'month_asc': 0, 'month_desc': 3},
  {'id': 4, 'month': 'July', 'month_asc': 0, 'month_desc': 2},
  {'id': 4, 'month': 'August', 'month_asc': 0, 'month_desc': 3},
  {'id': 4, 'month': 'September', 'month_asc': 0, 'month_desc': 2},
  {'id': 4, 'month': 'October', 'month_asc': 0, 'month_desc': 3},
  {'id': 4, 'month': 'November', 'month_asc': 0, 'month_desc': 2},
  {'id': 4, 'month': 'December', 'month_asc': 0, 'month_desc': 3}],
 [{'id': 5, 'month': 'January', 'month_asc': 0, 'month_desc': 2},
  {'id': 5, 'month': 'February', 'month_asc': 0, 'month_desc': 2},
  {'id': 5, 'month': 'March', 'month_asc': 0, 'month_desc': 3},
  {'id': 5, 'month': 'April', 'month_asc': 0, 'month_desc': 2},
  {'id': 5, 'month': 'May', 'month_asc': 0, 'month_desc': 2},
  {'id': 5, 'month': 'June', 'month_asc': 0, 'month_desc': 3},
  {'id': 5, 'month': 'July', 'month_asc': 0, 'month_desc': 2},
  {'id': 5, 'month': 'August', 'month_asc': 0, 'month_desc': 3},
  {'id': 5, 'month': 'September', 'month_asc': 0, 'month_desc': 2},
  {'id': 5, 'month': 'October', 'month_asc': 0, 'month_desc': 3},
  {'id': 5, 'month': 'November', 'month_asc': 0, 'month_desc': 2},
  {'id': 5, 'month': 'December', 'month_asc': 0, 'month_desc': 3}],
 [{'id': 6, 'month': 'January', 'month_asc': 0, 'month_desc': 2},
  {'id': 6, 'month': 'February', 'month_asc': 0, 'month_desc': 2},
  {'id': 6, 'month': 'March', 'month_asc': 0, 'month_desc': 3},
  {'id': 6, 'month': 'April', 'month_asc': 0, 'month_desc': 2},
  {'id': 6, 'month': 'May', 'month_asc': 0, 'month_desc': 2},
  {'id': 6, 'month': 'June', 'month_asc': 0, 'month_desc': 3},
  {'id': 6, 'month': 'July', 'month_asc': 0, 'month_desc': 2},
  {'id': 6, 'month': 'August', 'month_asc': 0, 'month_desc': 3},
  {'id': 6, 'month': 'September', 'month_asc': 0, 'month_desc': 2},
  {'id': 6, 'month': 'October', 'month_asc': 0, 'month_desc': 3},
  {'id': 6, 'month': 'November', 'month_asc': 0, 'month_desc': 2},
  {'id': 6, 'month': 'December', 'month_asc': 0, 'month_desc': 3}],
 [{'id': 7, 'month': 'January', 'month_asc': 3, 'month_desc': 3},
  {'id': 7, 'month': 'February', 'month_asc': 2, 'month_desc': 2},
  {'id': 7, 'month': 'March', 'month_asc': 3, 'month_desc': 3},
  {'id': 7, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 7, 'month': 'May', 'month_asc': 3, 'month_desc': 3},
  {'id': 7, 'month': 'June', 'month_asc': 1, 'month_desc': 2},
  {'id': 7, 'month': 'July', 'month_asc': 2, 'month_desc': 3},
  {'id': 7, 'month': 'August', 'month_asc': 3, 'month_desc': 2},
  {'id': 7, 'month': 'September', 'month_asc': 2, 'month_desc': 3},
  {'id': 7, 'month': 'October', 'month_asc': 2, 'month_desc': 2},
  {'id': 7, 'month': 'November', 'month_asc': 2, 'month_desc': 3},
  {'id': 7, 'month': 'December', 'month_asc': 3, 'month_desc': 2}],
 [{'id': 8, 'month': 'January', 'month_asc': 3, 'month_desc': 3},
  {'id': 8, 'month': 'February', 'month_asc': 2, 'month_desc': 2},
  {'id': 8, 'month': 'March', 'month_asc': 3, 'month_desc': 3},
  {'id': 8, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 8, 'month': 'May', 'month_asc': 3, 'month_desc': 3},
  {'id': 8, 'month': 'June', 'month_asc': 1, 'month_desc': 2},
  {'id': 8, 'month': 'July', 'month_asc': 2, 'month_desc': 3},
  {'id': 8, 'month': 'August', 'month_asc': 3, 'month_desc': 2},
  {'id': 8, 'month': 'September', 'month_asc': 2, 'month_desc': 3},
  {'id': 8, 'month': 'October', 'month_asc': 2, 'month_desc': 2},
  {'id': 8, 'month': 'November', 'month_asc': 2, 'month_desc': 3},
  {'id': 8, 'month': 'December', 'month_asc': 3, 'month_desc': 2}],
 [{'id': 9, 'month': 'January', 'month_asc': 3, 'month_desc': 6},
  {'id': 9, 'month': 'February', 'month_asc': 2, 'month_desc': 4},
  {'id': 9, 'month': 'March', 'month_asc': 3, 'month_desc': 6},
  {'id': 9, 'month': 'April', 'month_asc': 2, 'month_desc': 4},
  {'id': 9, 'month': 'May', 'month_asc': 3, 'month_desc': 6},
  {'id': 9, 'month': 'June', 'month_asc': 1, 'month_desc': 4},
  {'id': 9, 'month': 'July', 'month_asc': 2, 'month_desc': 6},
  {'id': 9, 'month': 'August', 'month_asc': 3, 'month_desc': 4},
  {'id': 9, 'month': 'September', 'month_asc': 2, 'month_desc': 6},
  {'id': 9, 'month': 'October', 'month_asc': 2, 'month_desc': 4},
  {'id': 9, 'month': 'November', 'month_asc': 2, 'month_desc': 6},
  {'id': 9, 'month': 'December', 'month_asc': 3, 'month_desc': 4}],
 [{'id': 10, 'month': 'January', 'month_asc': 3, 'month_desc': 3},
  {'id': 10, 'month': 'February', 'month_asc': 2, 'month_desc': 2},
  {'id': 10, 'month': 'March', 'month_asc': 3, 'month_desc': 3},
  {'id': 10, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 10, 'month': 'May', 'month_asc': 3, 'month_desc': 3},
  {'id': 10, 'month': 'June', 'month_asc': 1, 'month_desc': 2},
  {'id': 10, 'month': 'July', 'month_asc': 2, 'month_desc': 3},
  {'id': 10, 'month': 'August', 'month_asc': 3, 'month_desc': 2},
  {'id': 10, 'month': 'September', 'month_asc': 2, 'month_desc': 3},
  {'id': 10, 'month': 'October', 'month_asc': 2, 'month_desc': 2},
  {'id': 10, 'month': 'November', 'month_asc': 2, 'month_desc': 3},
  {'id': 10, 'month': 'December', 'month_asc': 3, 'month_desc': 2}],
 [{'id': 11, 'month': 'January', 'month_asc': 3, 'month_desc': 4},
  {'id': 11, 'month': 'February', 'month_asc': 2, 'month_desc': 3},
  {'id': 11, 'month': 'March', 'month_asc': 3, 'month_desc': 5},
  {'id': 11, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 11, 'month': 'May', 'month_asc': 3, 'month_desc': 3},
  {'id': 11, 'month': 'June', 'month_asc': 1, 'month_desc': 2},
  {'id': 11, 'month': 'July', 'month_asc': 2, 'month_desc': 5},
  {'id': 11, 'month': 'August', 'month_asc': 3, 'month_desc': 4},
  {'id': 11, 'month': 'September', 'month_asc': 2, 'month_desc': 4},
  {'id': 11, 'month': 'October', 'month_asc': 2, 'month_desc': 3},
  {'id': 11, 'month': 'November', 'month_asc': 2, 'month_desc': 4},
  {'id': 11, 'month': 'December', 'month_asc': 3, 'month_desc': 4}],
 [{'id': 12, 'month': 'January', 'month_asc': 3, 'month_desc': 2},
  {'id': 12, 'month': 'February', 'month_asc': 2, 'month_desc': 3},
  {'id': 12, 'month': 'March', 'month_asc': 2, 'month_desc': 2},
  {'id': 12, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 12, 'month': 'May', 'month_asc': 3, 'month_desc': 2},
  {'id': 12, 'month': 'June', 'month_asc': 2, 'month_desc': 2},
  {'id': 12, 'month': 'July', 'month_asc': 3, 'month_desc': 2},
  {'id': 12, 'month': 'August', 'month_asc': 2, 'month_desc': 3},
  {'id': 12, 'month': 'September', 'month_asc': 3, 'month_desc': 1},
  {'id': 12, 'month': 'October', 'month_asc': 2, 'month_desc': 3},
  {'id': 12, 'month': 'November', 'month_asc': 3, 'month_desc': 2},
  {'id': 12, 'month': 'December', 'month_asc': 2, 'month_desc': 1}],
 [{'id': 13, 'month': 'January', 'month_asc': 3, 'month_desc': 2},
  {'id': 13, 'month': 'February', 'month_asc': 2, 'month_desc': 3},
  {'id': 13, 'month': 'March', 'month_asc': 2, 'month_desc': 2},
  {'id': 13, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 13, 'month': 'May', 'month_asc': 3, 'month_desc': 2},
  {'id': 13, 'month': 'June', 'month_asc': 2, 'month_desc': 2},
  {'id': 13, 'month': 'July', 'month_asc': 3, 'month_desc': 2},
  {'id': 13, 'month': 'August', 'month_asc': 2, 'month_desc': 3},
  {'id': 13, 'month': 'September', 'month_asc': 3, 'month_desc': 1},
  {'id': 13, 'month': 'October', 'month_asc': 2, 'month_desc': 3},
  {'id': 13, 'month': 'November', 'month_asc': 3, 'month_desc': 2},
  {'id': 13, 'month': 'December', 'month_asc': 2, 'month_desc': 1}],
 [{'id': 14, 'month': 'January', 'month_asc': 3, 'month_desc': 2},
  {'id': 14, 'month': 'February', 'month_asc': 2, 'month_desc': 3},
  {'id': 14, 'month': 'March', 'month_asc': 2, 'month_desc': 2},
  {'id': 14, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 14, 'month': 'May', 'month_asc': 3, 'month_desc': 2},
  {'id': 14, 'month': 'June', 'month_asc': 2, 'month_desc': 2},
  {'id': 14, 'month': 'July', 'month_asc': 3, 'month_desc': 2},
  {'id': 14, 'month': 'August', 'month_asc': 2, 'month_desc': 3},
  {'id': 14, 'month': 'September', 'month_asc': 3, 'month_desc': 1},
  {'id': 14, 'month': 'October', 'month_asc': 2, 'month_desc': 3},
  {'id': 14, 'month': 'November', 'month_asc': 3, 'month_desc': 2},
  {'id': 14, 'month': 'December', 'month_asc': 2, 'month_desc': 1}],
 [{'id': 15, 'month': 'January', 'month_asc': 3, 'month_desc': 2},
  {'id': 15, 'month': 'February', 'month_asc': 2, 'month_desc': 3},
  {'id': 15, 'month': 'March', 'month_asc': 2, 'month_desc': 2},
  {'id': 15, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 15, 'month': 'May', 'month_asc': 3, 'month_desc': 2},
  {'id': 15, 'month': 'June', 'month_asc': 2, 'month_desc': 2},
  {'id': 15, 'month': 'July', 'month_asc': 3, 'month_desc': 2},
  {'id': 15, 'month': 'August', 'month_asc': 2, 'month_desc': 3},
  {'id': 15, 'month': 'September', 'month_asc': 3, 'month_desc': 1},
  {'id': 15, 'month': 'October', 'month_asc': 2, 'month_desc': 3},
  {'id': 15, 'month': 'November', 'month_asc': 3, 'month_desc': 2},
  {'id': 15, 'month': 'December', 'month_asc': 2, 'month_desc': 1}],
 [{'id': 16, 'month': 'January', 'month_asc': 3, 'month_desc': 2},
  {'id': 16, 'month': 'February', 'month_asc': 2, 'month_desc': 3},
  {'id': 16, 'month': 'March', 'month_asc': 2, 'month_desc': 2},
  {'id': 16, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 16, 'month': 'May', 'month_asc': 3, 'month_desc': 2},
  {'id': 16, 'month': 'June', 'month_asc': 2, 'month_desc': 2},
  {'id': 16, 'month': 'July', 'month_asc': 3, 'month_desc': 2},
  {'id': 16, 'month': 'August', 'month_asc': 2, 'month_desc': 3},
  {'id': 16, 'month': 'September', 'month_asc': 3, 'month_desc': 1},
  {'id': 16, 'month': 'October', 'month_asc': 2, 'month_desc': 3},
  {'id': 16, 'month': 'November', 'month_asc': 3, 'month_desc': 2},
  {'id': 16, 'month': 'December', 'month_asc': 2, 'month_desc': 1}],
 [{'id': 17, 'month': 'January', 'month_asc': 3, 'month_desc': 2},
  {'id': 17, 'month': 'February', 'month_asc': 2, 'month_desc': 3},
  {'id': 17, 'month': 'March', 'month_asc': 2, 'month_desc': 2},
  {'id': 17, 'month': 'April', 'month_asc': 4, 'month_desc': 2},
  {'id': 17, 'month': 'May', 'month_asc': 4, 'month_desc': 2},
  {'id': 17, 'month': 'June', 'month_asc': 2, 'month_desc': 2},
  {'id': 17, 'month': 'July', 'month_asc': 4, 'month_desc': 2},
  {'id': 17, 'month': 'August', 'month_asc': 5, 'month_desc': 3},
  {'id': 17, 'month': 'September', 'month_asc': 5, 'month_desc': 1},
  {'id': 17, 'month': 'October', 'month_asc': 5, 'month_desc': 3},
  {'id': 17, 'month': 'November', 'month_asc': 5, 'month_desc': 2},
  {'id': 17, 'month': 'December', 'month_asc': 5, 'month_desc': 1}],
 [{'id': 18, 'month': 'January', 'month_asc': 3, 'month_desc': 2},
  {'id': 18, 'month': 'February', 'month_asc': 2, 'month_desc': 3},
  {'id': 18, 'month': 'March', 'month_asc': 2, 'month_desc': 2},
  {'id': 18, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 18, 'month': 'May', 'month_asc': 3, 'month_desc': 2},
  {'id': 18, 'month': 'June', 'month_asc': 2, 'month_desc': 2},
  {'id': 18, 'month': 'July', 'month_asc': 3, 'month_desc': 2},
  {'id': 18, 'month': 'August', 'month_asc': 2, 'month_desc': 3},
  {'id': 18, 'month': 'September', 'month_asc': 3, 'month_desc': 1},
  {'id': 18, 'month': 'October', 'month_asc': 2, 'month_desc': 3},
  {'id': 18, 'month': 'November', 'month_asc': 3, 'month_desc': 2},
  {'id': 18, 'month': 'December', 'month_asc': 2, 'month_desc': 1}],
 [{'id': 19, 'month': 'January', 'month_asc': 3, 'month_desc': 2},
  {'id': 19, 'month': 'February', 'month_asc': 2, 'month_desc': 3},
  {'id': 19, 'month': 'March', 'month_asc': 2, 'month_desc': 2},
  {'id': 19, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 19, 'month': 'May', 'month_asc': 3, 'month_desc': 2},
  {'id': 19, 'month': 'June', 'month_asc': 2, 'month_desc': 2},
  {'id': 19, 'month': 'July', 'month_asc': 3, 'month_desc': 2},
  {'id': 19, 'month': 'August', 'month_asc': 2, 'month_desc': 3},
  {'id': 19, 'month': 'September', 'month_asc': 3, 'month_desc': 1},
  {'id': 19, 'month': 'October', 'month_asc': 2, 'month_desc': 3},
  {'id': 19, 'month': 'November', 'month_asc': 3, 'month_desc': 2},
  {'id': 19, 'month': 'December', 'month_asc': 2, 'month_desc': 1}],
 [{'id': 20, 'month': 'January', 'month_asc': 3, 'month_desc': 2},
  {'id': 20, 'month': 'February', 'month_asc': 2, 'month_desc': 3},
  {'id': 20, 'month': 'March', 'month_asc': 2, 'month_desc': 2},
  {'id': 20, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 20, 'month': 'May', 'month_asc': 3, 'month_desc': 2},
  {'id': 20, 'month': 'June', 'month_asc': 2, 'month_desc': 2},
  {'id': 20, 'month': 'July', 'month_asc': 3, 'month_desc': 2},
  {'id': 20, 'month': 'August', 'month_asc': 2, 'month_desc': 3},
  {'id': 20, 'month': 'September', 'month_asc': 3, 'month_desc': 1},
  {'id': 20, 'month': 'October', 'month_asc': 2, 'month_desc': 3},
  {'id': 20, 'month': 'November', 'month_asc': 3, 'month_desc': 2},
  {'id': 20, 'month': 'December', 'month_asc': 2, 'month_desc': 1}],
 [{'id': 21, 'month': 'January', 'month_asc': 3, 'month_desc': 5},
  {'id': 21, 'month': 'February', 'month_asc': 2, 'month_desc': 5},
  {'id': 21, 'month': 'March', 'month_asc': 2, 'month_desc': 5},
  {'id': 21, 'month': 'April', 'month_asc': 2, 'month_desc': 4},
  {'id': 21, 'month': 'May', 'month_asc': 3, 'month_desc': 5},
  {'id': 21, 'month': 'June', 'month_asc': 2, 'month_desc': 4},
  {'id': 21, 'month': 'July', 'month_asc': 3, 'month_desc': 5},
  {'id': 21, 'month': 'August', 'month_asc': 2, 'month_desc': 5},
  {'id': 21, 'month': 'September', 'month_asc': 3, 'month_desc': 4},
  {'id': 21, 'month': 'October', 'month_asc': 2, 'month_desc': 5},
  {'id': 21, 'month': 'November', 'month_asc': 3, 'month_desc': 5},
  {'id': 21, 'month': 'December', 'month_asc': 2, 'month_desc': 3}],
 [{'id': 22, 'month': 'January', 'month_asc': 3, 'month_desc': 3},
  {'id': 22, 'month': 'February', 'month_asc': 2, 'month_desc': 2},
  {'id': 22, 'month': 'March', 'month_asc': 3, 'month_desc': 3},
  {'id': 22, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 22, 'month': 'May', 'month_asc': 3, 'month_desc': 3},
  {'id': 22, 'month': 'June', 'month_asc': 1, 'month_desc': 2},
  {'id': 22, 'month': 'July', 'month_asc': 2, 'month_desc': 3},
  {'id': 22, 'month': 'August', 'month_asc': 3, 'month_desc': 2},
  {'id': 22, 'month': 'September', 'month_asc': 2, 'month_desc': 3},
  {'id': 22, 'month': 'October', 'month_asc': 2, 'month_desc': 2},
  {'id': 22, 'month': 'November', 'month_asc': 2, 'month_desc': 3},
  {'id': 22, 'month': 'December', 'month_asc': 3, 'month_desc': 2}],
 [{'id': 23, 'month': 'January', 'month_asc': 3, 'month_desc': 2},
  {'id': 23, 'month': 'February', 'month_asc': 2, 'month_desc': 3},
  {'id': 23, 'month': 'March', 'month_asc': 2, 'month_desc': 2},
  {'id': 23, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 23, 'month': 'May', 'month_asc': 3, 'month_desc': 2},
  {'id': 23, 'month': 'June', 'month_asc': 2, 'month_desc': 2},
  {'id': 23, 'month': 'July', 'month_asc': 3, 'month_desc': 2},
  {'id': 23, 'month': 'August', 'month_asc': 2, 'month_desc': 3},
  {'id': 23, 'month': 'September', 'month_asc': 3, 'month_desc': 1},
  {'id': 23, 'month': 'October', 'month_asc': 2, 'month_desc': 3},
  {'id': 23, 'month': 'November', 'month_asc': 3, 'month_desc': 2},
  {'id': 23, 'month': 'December', 'month_asc': 2, 'month_desc': 1}],
 [{'id': 24, 'month': 'January', 'month_asc': 3, 'month_desc': 2},
  {'id': 24, 'month': 'February', 'month_asc': 2, 'month_desc': 3},
  {'id': 24, 'month': 'March', 'month_asc': 2, 'month_desc': 2},
  {'id': 24, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 24, 'month': 'May', 'month_asc': 3, 'month_desc': 2},
  {'id': 24, 'month': 'June', 'month_asc': 2, 'month_desc': 2},
  {'id': 24, 'month': 'July', 'month_asc': 3, 'month_desc': 2},
  {'id': 24, 'month': 'August', 'month_asc': 2, 'month_desc': 3},
  {'id': 24, 'month': 'September', 'month_asc': 3, 'month_desc': 1},
  {'id': 24, 'month': 'October', 'month_asc': 2, 'month_desc': 3},
  {'id': 24, 'month': 'November', 'month_asc': 3, 'month_desc': 2},
  {'id': 24, 'month': 'December', 'month_asc': 2, 'month_desc': 1}],
 [{'id': 25, 'month': 'January', 'month_asc': 3, 'month_desc': 2},
  {'id': 25, 'month': 'February', 'month_asc': 2, 'month_desc': 3},
  {'id': 25, 'month': 'March', 'month_asc': 2, 'month_desc': 2},
  {'id': 25, 'month': 'April', 'month_asc': 2, 'month_desc': 2},
  {'id': 25, 'month': 'May', 'month_asc': 3, 'month_desc': 2},
  {'id': 25, 'month': 'June', 'month_asc': 2, 'month_desc': 2},
  {'id': 25, 'month': 'July', 'month_asc': 3, 'month_desc': 2},
  {'id': 25, 'month': 'August', 'month_asc': 2, 'month_desc': 3},
  {'id': 25, 'month': 'September', 'month_asc': 3, 'month_desc': 1},
  {'id': 25, 'month': 'October', 'month_asc': 2, 'month_desc': 3},
  {'id': 25, 'month': 'November', 'month_asc': 3, 'month_desc': 2},
  {'id': 25, 'month': 'December', 'month_asc': 2, 'month_desc': 1}],
 [{'id': 26, 'month': 'January', 'month_asc': 3, 'month_desc': 2},
  {'id': 26, 'month': 'February', 'month_asc': 2, 'month_desc': 3},
  {'id': 26, 'month': 'March', 'month_asc': 2, 'month_desc': 2},

In [30]:
import pandas as pd
# Flatten the list of lists
flattened_data = [item for sublist in data for item in sublist]

# Convert to a Pandas DataFrame
df = pd.DataFrame(flattened_data)

# Display the DataFrame
print(df)

       id      month  month_asc  month_desc
0       1    January          3           2
1       1   February          2           2
2       1      March          3           3
3       1      April          2           2
4       1        May          3           2
...   ...        ...        ...         ...
1843  182     August          3           2
1844  182  September          2           3
1845  182    October          2           2
1846  182   November          2           3
1847  182   December          3           2

[1848 rows x 4 columns]

In [31]:
df.to_csv('data.csv', index=False)

### Process  single runway

In [ ]:
# Select airstrip record
airstrip_gpd = projected_airstrip_training_gdf.iloc[1]

# Get information from the airstrip
year = int(airstrip_gpd.yr)
id = airstrip_gpd.id
airstrip_gpd_geometry = airstrip_gpd.geometry

# Create a square buffer at a distance of 5 km around centroid of airstrip
buffer_gpd = Point(airstrip_gpd_geometry.centroid).buffer(1000, cap_style=3)

# Convert GeoPandas geometry to Earth Engine features
airstrip_ee = gpd_geometry_to_ee_geometry(airstrip_gpd_geometry)
buffer_ee = gpd_geometry_to_ee_geometry(buffer_gpd)

# Download monthly composites
# GEE expects the aoi to be in geogprahic coordinates to filter the image collection
# img = download_sentinel1_data(buffer_ee, id)
info = download_sentinel1_data(buffer_ee, id)
info

In [111]:
# Create a map
m = geemap.Map()

# Visualization params
vis_params = {
    'min': -30,
    'max': 100,
    #'palette': ['blue', 'green', 'red']
}

# Display the map
m.centerObject(buffer_ee, zoom=15)

# Enable layer control
m.addLayerControl()

# Add layers
m.addLayer(img[1], vis_params, 'SAR')
m.addLayer(airstrip_ee, {'color': 'red', 'width': 1}, 'Airstrip')

m

Map(center=[-13.616470429757568, -69.17015088567591], controls=(WidgetControl(options=['position', 'transparen…

In [26]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from oauth2client.service_account import ServiceAccountCredentials

# authenticate to Google Drive (of the Service account)
#service_account = 'earth-engine-sa@ee-runway-detection.iam.gserviceaccount.com'
#credentials = ee.ServiceAccountCredentials(service_account, '/content/ee-runway-detection-ce5179ca616c.json')

gauth = GoogleAuth()
scopes = ['https://www.googleapis.com/auth/drive']
gauth.credentials = ServiceAccountCredentials.from_json_keyfile_name('/content/ee-runway-detection-ce5179ca616c.json', scopes=scopes)

drive = GoogleDrive(gauth)

In [32]:
from google.oauth2 import service_account
from googleapiclient.discovery import build
import io
from googleapiclient.http import MediaIoBaseDownload

# Path to your service account key file
SERVICE_ACCOUNT_FILE = '/content/ee-runway-detection-ce5179ca616c.json'

# Define the required scopes
SCOPES = ['https://www.googleapis.com/auth/drive']

# Authenticate using the service account
credentials = service_account.Credentials.from_service_account_file(
    SERVICE_ACCOUNT_FILE, scopes=SCOPES)

# Initialize the Google Drive service
drive_service = build('drive', 'v3', credentials=credentials)

# Function to download a file from Google Drive
def download_file(file_id, file_name):
    request = drive_service.files().get_media(fileId=file_id)
    fh = io.FileIO(file_name, 'wb')
    downloader = MediaIoBaseDownload(fh, request)
    done = False
    while done is False:
        status, done = downloader.next_chunk()
        print(f"Download {int(status.progress() * 100)}% complete.")
    print(f"File {file_name} downloaded successfully.")

# Example: List files in the service account's Google Drive
results = drive_service.files().list(
    pageSize=10, fields="nextPageToken, files(id, name)").execute()
items = results.get('files', [])

# Print the list of files in the Drive
if not items:
    print('No files found.')
else:
    print('Files:')
    for item in items:
        print(f"{item['name']} ({item['id']})")

# Download a specific file by its file ID
# Replace 'your-file-id' with the actual file ID and 'your-file-name' with the desired name
file_id = '1laCSccscSYJcC2RmiOCRHyfB8qXlc5WH'  # Replace with the file ID you want to download
file_name = 'Sentinel1_Composite_2_2023_01.tif'  # Replace with the desired local file name
download_file(file_id, file_name)

Files:
Sentinel1_Composite_2_2023_01.tif (1laCSccscSYJcC2RmiOCRHyfB8qXlc5WH)
Sentinel1_Composite_2_2023_02.tif (10DnqxGv1dSktCLB40Syb5tmR0weggm3p)
Colab Notebooks/GEE_Exports (1sJip4DGO9ABQ8DM28ESt-5wW6iIYjU5C)
Colab Notebooks/GEE_Exports (17ujqiU1kbte753XzgtH3VtCl5SS_SSwe)
GEE_Exports (1b1ZqdSvjijkgyX3t9qUw1bZyqcbdJ9w_)
Sentinel1_Composite_2_2023_02.tif (14-0RMjA_vMAUWs-ThTQcsKr18ke0IImV)
Sentinel1_Composite_2_2023_01.tif (1WsJlc9g37S2WiIGCF5UXysnggFPS9P4s)
Sentinel1_Composite_2_2023_01.tif (17E8BUf2o9nyguuIjhUPJetq5XWMYJWxs)
Sentinel1_Composite_2_2023_02.tif (1YIkQ1H5tiiSE4eCnvJmGWrnp0IPSUXJ5)
Colab Notebooks (1J5U7Ofd0z5gmKzof_GNvQh2pT1YSY6kl)
Download 100% complete.
File Sentinel1_Composite_2_2023_01.tif downloaded successfully.